name: .NET Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build_webapi:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: |
            6.0.x
    - name: Restore dependencies
      run: dotnet restore MyTemplate.sln
      working-directory: ./templates/aspnet.webapi
    - name: Build
      run: dotnet build --no-restore
      working-directory: ./templates/aspnet.webapi/src/MyTemplate.API
  build_grpc:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: |
            6.0.x
    - name: Restore dependencies
      run: dotnet restore MyTemplate.sln
      working-directory: ./templates/aspnet.grpc
    - name: Build
      run: dotnet build --no-restore
      working-directory: ./templates/aspnet.grpc/src/MyTemplate.API
